### ISSUE TITLE
parse Level.sav 出现问题

### ISSUE THREAD

**Issue by MapleEve** [magicbear/palworld-server-toolkit#1]
Traceback (most recent call last):
  File "D:\steamcmd\steamapps\common\PalServer\Pal\Saved\SaveGames\0\XXX\palworld-cleanup-tools.py", line 801, in <module>
    main()
  File "D:\steamcmd\steamapps\common\PalServer\Pal\Saved\SaveGames\0\XXX\palworld-cleanup-tools.py", line 87, in main
    ShowPlayers()
  File "D:\steamcmd\steamapps\common\PalServer\Pal\Saved\SaveGames\0\XXX\palworld-cleanup-tools.py", line 634, in ShowPlayers
    playerMeta['Level'] if 'Level' in playerMeta else -1, playerMeta['NickName']))

**Comment by MapleEve** [comment]
>>> DeletePlayer(3470463608)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\steamcmd\steamapps\common\PalServer\Pal\Saved\SaveGames\0\XXXXXXX\palworld-cleanup-tools.py", line 451, in DeletePlayer
    player_sav_file = os.path.dirname(os.path.abspath(args.filename)) + "/Players/" + player_uid.upper().replace("-",
                                                                                      ^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'upper'
