### ISSUE TITLE
KeyError: 'OwnerPlayerUId'

### ISSUE THREAD

**Issue by yamadafz** [magicbear/palworld-server-toolkit#102]
点击删除损坏对象就会出错

**Comment by alvinHRFM** [comment]
duplicated #101

**Comment by yamadafz** [comment]
新版还没出吗

**Comment by VYRNACH** [comment]
I encounter the same issue when running "Del Damage Instance":
```
ContainerID 99e77b0c-82a4-4ccc-829b-0eb1a5448e6c Invalid
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "palworld_server_toolkit\editor.py", line 2224, in delete_damage_container
  File "palworld_server_toolkit\editor.py", line 4357, in FindDamageRefContainer
  File "palworld_server_toolkit\editor.py", line 4141, in CharacterDescription
KeyError: 'OwnerPlayerUId'
```

**Comment by alvinHRFM** [comment]
> 新版还没出吗


In case you cannot run the latest version, you can download https://github.com/alvinHRFM/palworld-server-toolkit/releases/tag/0.8.5 and put it to the v0.8.3 folder to run v0.8.5.
