### ISSUE TITLE
as soon as I try to do anything

### ISSUE THREAD

**Issue by Bibo89** [magicbear/palworld-server-toolkit#108]
Traceback (most recent call last):
  File "palworld_server_toolkit\editor.py", line 1863, in delete_player
  File "palworld_server_toolkit\editor.py", line 4572, in DeletePlayer
  File "palworld_server_toolkit\editor.py", line 2666, in GetPlayerGvas
  File "palworld_save_tools\palsav.py", line 33, in decompress_sav_to_gvas
Exception: incorrect compressed length: 2503

**Comment by Bibo89** [comment]
but in the same saves made an hour before it worked
