### ISSUE TITLE
KeyError: 'inventoryInfo'

### ISSUE THREAD

**Issue by angrystar170** [magicbear/palworld-server-toolkit#114]
Exception in thread Thread-2 (load):
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\angry\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 1282, in load
    if player_gvas['inventoryInfo']['value'][idx_key]['value']['ID']['value'] \
       ~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'inventoryInfo'

**Comment by JackKuo-tw** [comment]
After applying this [PR](https://github.com/magicbear/palworld-server-toolkit/pull/119), I got another issue:
KeyError: 'IndividualId'
