### ISSUE TITLE
Exception: Warning: EOF not reached for BlastFurnace

### ISSUE THREAD

**Issue by Droidem** [magicbear/palworld-server-toolkit#115]
I'm receiving this error when trying to copy a local player to a server. 

```
>>> CopyPlayer("00000000-0000-0000-0000-000000000001", "3f2706bf-0000-0000-0000-000000000000", backup_wsd)
Loading for player file
Parsing .worldSaveData.MapObjectSaveData...Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\script\New folder\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 2855, in CopyPlayer
    DeletePlayer(new_player_uid,
  File "D:\script\New folder\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 4591, in DeletePlayer
    load_skipped_decode(wsd, ['ItemContainerSaveData', 'CharacterContainerSaveData', 'MapObjectSaveData',
  File "D:\script\New folder\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 201, in load_skipped_decode
    BatchParseItem(_worldSaveData, skip_paths, recursive=recursive,
  File "D:\script\New folder\palworld-server-toolkit\palworld_server_toolkit\..\palworld_server_toolkit\palobject.py", line 1571, in BatchParseItem
    parse_skiped_item(properties, skip_path, progress, recursive, sub_mp)
  File "D:\script\New folder\palworld-server-toolkit\palworld_server_toolkit\..\palworld_server_toolkit\palobject.py", line 1491, in parse_skiped_item
    decoded_properties = reader.property(properties["skip_type"], len(properties['value']),
  File "D:\script\New folder\palworld-server-toolkit\palworld_server_toolkit\..\palworld_server_toolkit\palobject.py", line 1066, in property
    return super().property(type_name, size, path, nested_caller_path)
  File "D:\script\New folder\palworld-server-toolkit\palworld_server_toolkit\../save_tools\palworld_save_tools\archive.py", line 396, in property
    value = self.custom_properties[path][0](self, type_name, size, path)
  File "D:\script\New folder\palworld-server-toolkit\palworld_server_toolkit\../save_tools\palworld_save_tools\rawdata\map_object.py", line 45, in decode
    map_concrete_model.decode_bytes(
  File "D:\script\New folder\palworld-server-toolkit\palworld_server_toolkit\../save_tools\palworld_save_tools\rawdata\map_concrete_model.py", line 441, in decode_bytes
    elif map_object_concrete_model == "PalMapObjectTorchModel":
Exception: Warning: EOF not reached for BlastFurnace PalMapObjectConvertItemModel: ori: 71635e16fe1ba04490eb5c1f6b5e895622daa048c417cd46b9ed76844b02fd510c000000436f70706572496e676f740000000000290000000000803f01000000 remaining: 4
```

**Comment by bullfrogberry** [comment]
having a similar issue with Palworld level.sav file
![cmd](https://github.com/magicbear/palworld-server-toolkit/assets/13040266/4f3d2a4e-6df7-4db5-aa30-e233da0e5e31)
