### ISSUE TITLE
delete error

### ISSUE THREAD

**Issue by xczsonn** [magicbear/palworld-server-toolkit#23]
and my save load is error why

Error: Item Container c6477e76-4579-63f1-eb56-70b1da31d316 not found
Traceback (most recent call last):
  File "\\192.168.11.14\NVME\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 1648, in delete_player
  File "\\192.168.11.14\NVME\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 2962, in DeletePlayer
  File "\\192.
[7947B324000000000000000000000000.zip](https://github.com/magicbear/palworld-server-
168.11.14\NVME\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 2559, in BatchDeleteMapObject
UnboundLocalError: cannot access local variable 'mapObject' where it is not associated with a value
[7947B324000000000000000000000000.zip](https://github.com/magicbear/palworld-server-toolkit/files/14228387/7947B324000000000000000000000000.zip)

ps. Maybe it's because it's a save that was moved using https://github.com/JannikBirn/palworld-host-save-fix/releases this. Can I fix this?

**Comment by magicbear** [comment]
fixed on v0.5.0
