### ISSUE TITLE
Editor Dont open v. 5.4

### ISSUE THREAD

**Issue by Falke95** [magicbear/palworld-server-toolkit#31]
Hey, When i will open the editor new realease from realease download exe.

The load map. Than stop

Traceback (most recent call last):
  File "\\192.168.11.14\NVME\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 3763, in <module>
  File "\\192.168.11.14\NVME\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 596, in main

**Comment by magicbear** [comment]
fixed
