### ISSUE TITLE
PalEdit failure

### ISSUE THREAD

**Issue by drewgilkey** [magicbear/palworld-server-toolkit#34]
Looks like maybe a PalEdit push broke the app:

Traceback (most recent call last):
  File "C:\Users\dgilk\Downloads\SerenaSaved\2\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 44, in <module>
    from PalEdit import PalEditConfig, PalEdit
  File "C:\Users\dgilk\Downloads\SerenaSaved\2\palworld-server-toolkit\palworld_server_toolkit\PalEdit\PalEdit.py", line 217
    match preset:
          ^
SyntaxError: invalid syntax

**Comment by drewgilkey** [comment]
Ok seems that 3.9 is not the minimum version anymore.
