### ISSUE TITLE
Edit Item Exception

### ISSUE THREAD

**Issue by eyebiz** [magicbear/palworld-server-toolkit#43]
When clicking the "Edit Item" button, I'm getting the following error message:

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1967, in __call__
  File "\\192.168.11.14\NVME\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 1883, in edit_player_item
  File "\\192.168.11.14\NVME\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 1348, in __init__
  File "\\192.168.11.14\NVME\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 2244, in GetPlayerGvas
  File "palworld_save_tools\palsav.py", line 10, in decompress_sav_to_gvas
    save_type = data[11]
                ~~~~^^^^
IndexError: index out of range

I'll attach an image as well.
![Exception](https://github.com/magicbear/palworld-server-toolkit/assets/23479232/e0941937-adff-4639-adf2-3ef2518c171b)

**Comment by eyebiz** [comment]
For some reason 1 of the files in Players subfolder was 0 bytes.
I replaced this file with a file from an earlier backup, which solved the issue.

Thanks for this great tool!
