### ISSUE TITLE
Missing palworld-save-editor.png

### ISSUE THREAD

**Issue by jkroepke** [magicbear/palworld-server-toolkit#58]
I tried to run the Editor GUI from local source, but the png is missing

https://github.com/magicbear/palworld-server-toolkit/blob/679da09bf3236b6cce162df321c0af920f6de725/palworld_server_toolkit/editor.py#L1962

```
Failed to create GUI
Traceback (most recent call last):
  File "C:\Users\Jan\Downloads\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 4775, in <module>
    main()
  File "C:\Users\Jan\Downloads\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 587, in main
    gui_thread()
  File "C:\Users\Jan\Downloads\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 427, in gui_thread
    gui = GUI()
          ^^^^^
  File "C:\Users\Jan\Downloads\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 1425, in __init__
    self.build_gui()
  File "C:\Users\Jan\Downloads\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 1962, in build_gui
    self.gui.iconphoto(True, tk.PhotoImage(file=f'{module_dir}/resources/palworld-save-editor.png'))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jan\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 4140, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Users\Jan\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 4087, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "C:\Users\Jan\Downloads\palworld-server-toolkit\palworld_server_toolkit/resources/palworld-save-editor.png": no such file or directory
```

**Comment by magicbear** [comment]
fixed
