### ISSUE TITLE
Character Cleanup not functioning - TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by VYRNACH** [magicbear/palworld-server-toolkit#71]
I get this error when I try to run the "Character Cleanup" feature. Any ideas?
`Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1967, in __call__
  File "\\192.168.11.14\nvme\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 1905, in cleanup_character
  File "\\192.168.11.14\nvme\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 3567, in FindAllUnreferencedCharacterContainerIds
  File "\\192.168.11.14\nvme\Pal-Server\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 3558, in FindReferenceCharacterContainerIds
TypeError: unhashable type: 'dict'`

**Comment by magicbear** [comment]
fixed on 0.7.6

**Comment by VYRNACH** [comment]
thanks alot for the quick fix! Your work really helped the community alot!
