### ISSUE TITLE
CopyBaseCamp Issue With 0.8.1

### ISSUE THREAD

**Issue by krulci** [magicbear/palworld-server-toolkit#84]
Below output is with `dry_run=False`
```py
>>> CopyBaseCamp("d884ef80-4fcd-a2e4-a959-89b76378e58b","5427f1b4-4a85-e9f6-3268-279f4e4e9af6", backup_wsd)
Parsing .worldSaveData.MapObjectSaveData...Done in 5.13s
Loading .worldSaveData.MapObjectSpawnerInStageSaveData in 5.19s, extra parse 0.00s
Parse skipped data in 5.19s
Parsing .worldSaveData.MapObjectSaveData...Done in 7.64s
Loading .worldSaveData.MapObjectSpawnerInStageSaveData in 7.71s, extra parse 0.00s
Parse skipped data in 7.71s
INFO    : Copy Group UUID 5427f1b4-4a85-e9f6-3268-279f4e4e9af6  Map Instance ID d9d7727e-433f-99e9-7aa7-29828cbf2549
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\_\source\repos\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 4865, in CopyBaseCamp
    CopyMapObject(baseCamp['RawData']['value']['owner_map_object_instance_id'], old_wsd, dry_run)
  File "C:\Users\_\source\repos\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 3446, in CopyMapObject
    wsd['MapObjectSaveData']['value']['values'].append(mapObject)
                                                       ^^^^^^^^^
UnboundLocalError: cannot access local variable 'mapObject' where it is not associated with a value
```
Below output is with `dry_run=True`
```py
>>> CopyBaseCamp("d884ef80-4fcd-a2e4-a959-89b76378e58b","5427f1b4-4a85-e9f6-3268-279f4e4e9af6", backup_wsd, True)
Parsing .worldSaveData.MapObjectSaveData...Done in 5.49s
Loading .worldSaveData.MapObjectSpawnerInStageSaveData in 5.55s, extra parse 0.00s
Parse skipped data in 5.55s
Parsing .worldSaveData.MapObjectSaveData...Done in 7.75s
Loading .worldSaveData.MapObjectSpawnerInStageSaveData in 7.81s, extra parse 0.00s
Parse skipped data in 7.81s
INFO    : Copy Group UUID 5427f1b4-4a85-e9f6-3268-279f4e4e9af6  Map Instance ID d9d7727e-433f-99e9-7aa7-29828cbf2549
INFO    : Clone MapObject d9d7727e-433f-99e9-7aa7-29828cbf2549
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\_\source\repos\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 4865, in CopyBaseCamp
    CopyMapObject(baseCamp['RawData']['value']['owner_map_object_instance_id'], old_wsd, dry_run)
  File "C:\Users\_\source\repos\palworld-server-toolkit\palworld_server_toolkit\editor.py", line 3454, in CopyMapObject
    wsd['MapObjectSaveData']['value'].append(mapObject)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'append'
```
Both error results in Terminal and Interactive Mode.

**Comment by magicbear** [comment]
fixed on 0.8.2
