### ISSUE TITLE
Broken Base After Migration

### ISSUE THREAD

**Issue by krulci** [magicbear/palworld-server-toolkit#86]
This happens after base is migrated.
Upon login from any users.
Server stops.
On click "Adjust Slot" after selecting the migrated base as the target base, we get the following error in console:
```py
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "palworld_server_toolkit\editor.py", line 1875, in adjust_base_slot_count
KeyError: palworld_save_tools.archive.UUID('71c75e4c-4476-bd1d-7fdb-c5bc91ecfdab')
```

**Comment by krulci** [comment]
Below is `Diagnostics.txt` after server crashed:
```
Generating report for minidump

Application version 5.1.1.0
 ... built from changelist 0

OS version Linux 6.1.0-18-cloud-amd64 (network name: instance.asia-northeast1-a.c.loyal-bounty-412213.internal)
Running 2 x86_64 processors (4 logical cores)
Exception was "SIGSEGV: invalid attempt to read memory at address 0x0000000000000080"

<SOURCE START>
<SOURCE END>

<CALLSTACK START>
PalServer-Linux-Test!UPalBaseCampWorkerDirector::OnTickInServer_WaitForLoadingAround() [G:/works/repos/Pal_SVN/Pal-UE-App/Source/Pal/PalBaseCampWorkerDirector.cpp:1641]
PalServer-Linux-Test!UPalBaseCampModel::TickByManager(float) [G:/works/repos/Pal_SVN/Pal-UE-App/Source/Pal/PalBaseCampModel.cpp:205]
PalServer-Linux-Test!UPalBaseCampManager::Tick_ServerInternal(float) [G:/works/repos/Pal_SVN/Pal-UE-App/Source/Pal/PalBaseCampManager.cpp:505]
PalServer-Linux-Test!FTickableGameObject::TickObjects(UWorld*, int, bool, float) [C:/works/Pal-UE-EngineSource/Engine/Source/./Runtime/Engine/Private/Tickable.cpp:150]
PalServer-Linux-Test!UWorld::Tick(ELevelTick, float) [C:/works/Pal-UE-EngineSource/Engine/Source/./Runtime/Engine/Private/LevelTick.cpp:1606]
PalServer-Linux-Test!UGameEngine::Tick(float, bool) [C:/works/Pal-UE-EngineSource/Engine/Source/./Runtime/Engine/Private/GameEngine.cpp:1775]
PalServer-Linux-Test!FEngineLoop::Tick() [C:/works/Pal-UE-EngineSource/Engine/Source/./Runtime/Launch/Private/LaunchEngineLoop.cpp:5363]
PalServer-Linux-Test!GuardedMain(char16_t const*) [C:/works/Pal-UE-EngineSource/Engine/Source/./Runtime/Launch/Private/Launch.cpp:204]
PalServer-Linux-Test!CommonUnixMain(int, char**, int (*)(char16_t const*), void (*)()) [C:/works/Pal-UE-EngineSource/Engine/Source/Runtime/Unix/UnixCommonStartup/Private/UnixCommonStartup.cpp:269]
libc.so.6!UnknownFunction(0x27249)
libc.so.6!__libc_start_main(+0x84)
PalServer-Linux-Test!_start()

<CALLSTACK END>

0 loaded modules

Report end!
```
