### ISSUE TITLE
[v0.1.5.0] "Del Damage Instance" breaks

### ISSUE THREAD

**Issue by VYRNACH** [magicbear/palworld-server-toolkit#91]
For the latest v0.1.5.0, "Del Damage Instance" breaks. Seems like a change in format?

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "palworld_server_toolkit\editor.py", line 2224, in delete_damage_container
  File "palworld_server_toolkit\editor.py", line 4357, in FindDamageRefContainer
  File "palworld_server_toolkit\editor.py", line 4141, in CharacterDescription
KeyError: 'OwnerPlayerUId'
```

**Comment by magicbear** [comment]
Fixed on 0.8.4
